### ISSUE TITLE
Latest 0.13 mac build crashes

### ISSUE THREAD

**Issue by bkostjens** [zoinofficial/zoin#20]
Hi,

Running macOS 10.13.2 the latest 0.13.0.0 (9ea97c4) build crashes on launch. The 'older' 0.13 build worked fine.

Crash report:

Process:               zoin-qt [29805]
Path:                  /Applications/zoin-qt.app/Contents/MacOS/zoin-qt
Identifier:            zoinofficial.zoin-qt
Version:               0.13.0 (0.13.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           zoin-qt [29805]
User ID:               502

Date/Time:             2018-01-17 10:56:17.736 +0100
OS Version:            Mac OS X 10.13.2 (17C205)
Report Version:        12
Anonymous UUID:        142DD1FF-FCDA-FC2E-77DB-0451F1EFCF1C

Sleep/Wake UUID:       8690E7C0-4849-41B6-A703-21CC858EFF9E

Time Awake Since Boot: 83000 seconds
Time Since Wake:       8500 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/boost/lib/libboost_system.dylib
  Referenced from: /Applications/zoin-qt.app/Contents/MacOS/zoin-qt
  Reason: image not found

Binary Images:
       0x106430000 -        0x1080c0ff7 +zoinofficial.zoin-qt (0.13.0 - 0.13.0) <9502245D-575E-366A-A7D1-7F886F7BB6A0> /Applications/zoin-qt.app/Contents/MacOS/zoin-qt
       0x10fda6000 -        0x10fdf098f  dyld (519.2.2) <6695F30B-4E88-3C0B-9867-7D738C44A3E6> /usr/lib/dyld

**Comment by mattt21** [comment]
Hey @bkostjens this will be patched in the next minor update as well as price indications and other known bugs - thanks for the info.
