### ISSUE TITLE
reindex blockchain & stuck

### ISSUE THREAD

**Issue by Volodya1234** [zoinofficial/zoin#21]
Hi!

I deleted all the files in a clean blockchain through my wallet.
After I left my wallet and went back wallet was initiates reindexing.
Re-indexing hangs on the block: 230180.

I think this is due to roll back blockchain from 231432 -> 230180.

Owners of pools that simple users can correct the problem.

**Comment by xamasa98** [comment]
Did you reindex or completely redownload the blockchain?

**Comment by Volodya1234** [comment]
Redownload. 

After I close wallet & open i have:
https://i.13.yt/2018/01/18/1516286193-3678.png

**Comment by xamasa98** [comment]
The last thing you experienced is related to #22 
Were you able to sync completely after reindexing?

**Comment by xamasa98** [comment]
Ok, this issue is already described in #22 . I'll close this ticket as it is the same problem.
