### ISSUE TITLE
Windows 0.13 Wallet - Blockchain Corruption on Close

### ISSUE THREAD

**Issue by nfantis** [zoinofficial/zoin#22]
When closing the Windows wallet (File... Close) it appears the wallet is crashing rather than gracefully shutting down.  Relaunching the wallet produces a corruption message followed by reindexing.  

This is on Windows 10 with the latest wallet.  

I followed the instructions of removing the blockchain data in %APPDATA% and allowed the wallet to fully update through the network.  The blockchain bootstrap was not used.

**Comment by SuperSpe** [comment]
Same issue here. I have redownload the new version 0.13 (the second one) and redownload all the chain from scratch. Tooks several hours but did the trick. After closing the wallet and restarted, it says that the db was corrupted. 
After rebuilding, it's stuck on block  230174, with no source available but with 5 connections active. I have several client banned.
Same issue with other ppl from discord.

**Comment by xamasa98** [comment]
Same issue here, stuck on block 230204 after reindex. After closing and opening it again, it synced the missing blocks nearly instantly

**Comment by Volodya1234** [comment]
Solved of this problem.

You need download blockchain 14.01.2018: https://drive.google.com/file/d/1sV3kKL2m1nJribhFxyN3BoJLyfe-yunO/view
Put this blockchain in your wallet folder && wallet.dat
There is no sense in downloading the chain of blocks from scratch if it does not change it static, it's just time to save.

Startup wallet. Wallet asked: Reindex? Yes.

When the daemon reindex the blockchain, it is necessary to ban all peers which have a height: 230180 to 231000. Leave only those who have a height of +-10 blocks to the current at the moment.

Just example, this peer has stuck wallet on block:
![bannn](https://user-images.githubusercontent.com/9968928/35142821-348168ac-fd08-11e7-921b-23f32826e606.png)
This peers need banned, they do error: 
2018-01-18 17:01:18 ProcessMessages(headers, 68448 bytes) FAILED peer=16
2018-01-18 17:01:20 ProcessMessage.AcceptBlockHeader() total 845 blocks
2018-01-18 17:01:20 ERROR: AcceptBlockHeader: Consensus::CheckBlockHeader: b8acae77ae216da87b60ec57102e958a4c19a01b1cb65473a7fb977f702d64d9, high-hash, proof of work failed (code 16)
2018-01-18 17:01:20 Misbehaving: 84.3.179.207:49686 (0 -> 50)
2018-01-18 17:01:20 ERROR: invalid header received
2018-01-18 17:01:20 ProcessMessages(headers, 68448 bytes) FAILED peer=14

After updating version 13 of the purse through the rollback of the blockchain, it happened that different people have different block heights and hashes. To avoid this problem, you have to ban all other peers who have not the correct blockchain.

**Comment by mattt21** [comment]
Try downloading 13.0.1
