### ISSUE TITLE
Windows 10 & OSX Wallet Font Incosistencies

### ISSUE THREAD

**Issue by nfantis** [zoinofficial/zoin#23]
Both the Windows 10 and OSX wallet fonts have changed with the Core 0.13 update.  The fonts no longer match the marketing materials.  Although everything appears to be visible, the sizing and spacing is not as clean as with the previous wallets.

**Comment by StelioK** [comment]
A screenshot to show the incosistencies would have been amazing.

**Comment by nfantis** [comment]
It's pretty obvious, but sure:

**Marketing Material**
![image](https://user-images.githubusercontent.com/22967457/35157037-c074db80-fd00-11e7-8ca9-6cb80e78e847.png)

I will post the current wallet font when I get back to my Windows PC.

**Comment by igdee** [comment]
This GUI screenshot from Windows 10 QHD+ screen
![zoinwallet](https://user-images.githubusercontent.com/24210326/35157745-f39285fe-fd45-11e7-8a9c-6a16e8edeee1.jpg)

**Comment by igdee** [comment]
Yes the wallet has different disturbances on different screens. I guess it's from the font.

**Comment by StelioK** [comment]
@nfantis Mine is as marketing material.

**Comment by nfantis** [comment]
@StelioK Interesting - are you on Windows 10?

**Comment by StelioK** [comment]
yep Windows 10 64bit, intel cpu, no graphics card, 100% font scaling.

**Comment by mattt21** [comment]
@igdee There is a known bug that anything other than 100% scaling results in poor layout. This is in the release notes. I am closing this issue, check the release notes next time please.
