### ISSUE TITLE
Transactions show incorrect amount

### ISSUE THREAD

**Issue by bkostjens** [zoinofficial/zoin#28]
Wallet: Balance is correct: 3.13, however: if you sum the incoming transactions the balance should be 4.33
![unknown](https://user-images.githubusercontent.com/222645/35431222-ee1a1f70-027b-11e8-9631-866e7a0f3f85.png)

Checking block explorer:
![unknown-1](https://user-images.githubusercontent.com/222645/35431225-efd7cd76-027b-11e8-9677-4295253ce941.png)

So transactions in the wallet miss a 0: it displays: +1.5093636 but it should be: +1.05093636

It also displays incorrect in the transactions details.

Zoin wallet (v0.13.0.1-fcb35fe-unk (64-bit)) on macOS High Sierra.

**Comment by devender-yadav** [comment]
Hi @bkostjens,

][Off-topic] are there any docs for mining on mac machine?

Thanks!

**Comment by mattt21** [comment]
Download 0.13.0.2
