### ISSUE TITLE
0.13.0.2 compile issue

### ISSUE THREAD

**Issue by apocsurvivor** [zoinofficial/zoin#30]
Compile issue for 0.13.0.2 using OpenSuse Tumbleweed.

qt/receivecoinsdialog.cpp: In member function ‘void ReceiveCoinsDialog::on_showImportPrivateKey_clicked()’:
qt/receivecoinsdialog.cpp:409:9: error: ‘QRCodeDialog’ was not declared in this scope
         QRCodeDialog *dialog = new QRCodeDialog(address,  label, tab == ReceivingTab, this, QString::fromStdString(privkey.get_str()), true);
         ^~~~~~~~~~~~
qt/receivecoinsdialog.cpp:409:9: note: suggested alternative: ‘QFileDialog’
         QRCodeDialog *dialog = new QRCodeDialog(address,  label, tab == ReceivingTab, this, QString::fromStdString(privkey.get_str()), true);
         ^~~~~~~~~~~~
         QFileDialog
qt/receivecoinsdialog.cpp:409:23: error: ‘dialog’ was not declared in this scope
         QRCodeDialog *dialog = new QRCodeDialog(address,  label, tab == ReceivingTab, this, QString::fromStdString(privkey.get_str()), true);
                       ^~~~~~
qt/receivecoinsdialog.cpp:409:23: note: suggested alternative: ‘QDialog’
         QRCodeDialog *dialog = new QRCodeDialog(address,  label, tab == ReceivingTab, this, QString::fromStdString(privkey.get_str()), true);
                       ^~~~~~
                       QDialog
qt/receivecoinsdialog.cpp:409:36: error: expected type-specifier before ‘QRCodeDialog’
         QRCodeDialog *dialog = new QRCodeDialog(address,  label, tab == ReceivingTab, this, QString::fromStdString(privkey.get_str()), true);
                                    ^~~~~~~~~~~~

**Comment by mattt21** [comment]
USE_QRCODE needs to be configured when compiling. If you are still having issues, read the documentation in the repo.
