### ISSUE TITLE
Zoin Core Wallet Version 0.13.0.2 Update - Windows 10 - Block 233001 error/not accept

### ISSUE THREAD

**Issue by Nietzsche2018** [zoinofficial/zoin#31]
So, the Zoin Core Wallet Version 0.13.0.2's reindex finished  
but the Wallet not sync and i can see an erro in debug log:
 CPOW: Amount Error 233001
 ERROR: AcceptBlockHeader: Consensus::CheckBlockHeader: 34dbf665edc8441aaba2b0aad17dea8fb951a8c72a970743419da501fa934fa5, high-hash, proof of work failed (code 16)
Invalid AcceptBlockHeader()
block nHeight=233001 IS NOT ACCEPTED!

FYI: the old Zoin Core Wallet Version 0.13.0.1 is working perfect

**Comment by mattt21** [comment]
You reindexed the wallet and received this error? If so, try redownloading the chain from scratch.

**Comment by Nietzsche2018** [comment]
Mattt21,
I redownloaded the chain a few days ago and finally it is working fine.

tks a lot.
